import os
import re
import subprocess
import glob

class RegressionTester:
    def __init__(self, workspace_dir, log_func=print):
        self.workspace = workspace_dir
        self.script_dir = os.path.join(workspace_dir, "simulation_env", "script")
        self.logger = log_func

    def parse_deploy_output(self, deploy_stdout):
        """
        Extract the latest deployed contract addresses from Deploy.s.sol output.
        """
        addresses = {}
        # Match output such as console.log("TARGET:", 0x...).
        # Deploy.s.sol emits a stable format suitable for this parser.
        patterns = {
            "TARGET": r"TARGET:\s*(0x[a-fA-F0-9]{40})",
            "TOKEN": r"MOCK_TOKEN:\s*(0x[a-fA-F0-9]{40})",
            "SAFETY": r"SAFETY_RULES:\s*(0x[a-fA-F0-9]{40})"
        }

        for key, pat in patterns.items():
            match = re.search(pat, deploy_stdout)
            if match:
                addresses[key] = match.group(1)

        return addresses

    def patch_and_run(self, deploy_stdout):
        """
        Patch deployed addresses into every Action_*.s.sol script and execute it.
        Return (passed_count, total_count, details).
        """
        # 1. Extract the new deployment addresses.
        new_addrs = self.parse_deploy_output(deploy_stdout)
        if "TARGET" not in new_addrs:
            self.logger("⚠️ Regression: Could not find TARGET address in deploy logs.")
            return 0, 0, []

        # 2. Locate historical action scripts, excluding deployment and safety scripts.
        # Treat action scripts as regression tests.
        scripts = glob.glob(os.path.join(self.script_dir, "Action_*.s.sol"))

        passed = 0
        total = 0
        results = []

        self.logger(f"   🔄 Starting Regression Test on {len(scripts)} accumulated scripts...")

        for script_path in scripts:
            script_name = os.path.basename(script_path)
            total += 1

            # Read the original script.
            with open(script_path, 'r', encoding='utf-8') as f:
                content = f.read()

            # === Address patching with regular expressions ===
            # Match the source layout generated by the pipeline.

            # 1. Replace targetAddr declarations.
            # Match: address targetAddr = 0x.....;
            if "TARGET" in new_addrs:
                content = re.sub(
                    r"address\s+targetAddr\s*=\s*0x[a-fA-F0-9]{40};",
                    f"address targetAddr = {new_addrs['TARGET']};",
                    content
                )
                # Support an alternate declaration style.
                content = re.sub(
                    r"StakingContract\s+target\s*=\s*StakingContract\(0x[a-fA-F0-9]{40}\);",
                    f"StakingContract target = StakingContract({new_addrs['TARGET']});",
                    content
                )

            # 2. Replace tokenAddr declarations.
            if "TOKEN" in new_addrs:
                content = re.sub(
                    r"address\s+tokenAddr\s*=\s*0x[a-fA-F0-9]{40};",
                    f"address tokenAddr = {new_addrs['TOKEN']};",
                    content
                )

            # 3. Replace SafetyRules addresses when present.
            if "SAFETY" in new_addrs:
                content = re.sub(
                    r"SafetyRules\s+rules\s*=\s*SafetyRules\(0x[a-fA-F0-9]{40}\);",
                    f"SafetyRules rules = SafetyRules({new_addrs['SAFETY']});",
                    content
                )

            # === Save and execute the patched temporary script ===
            temp_name = f"Regress_{script_name}"
            temp_path = os.path.join(self.script_dir, temp_name)

            with open(temp_path, 'w', encoding='utf-8') as f:
                f.write(content)

            # Execute the script with Forge against the local Anvil endpoint.
            # JSON output could support richer parsing, but the return code is sufficient here.
            cmd = [
                "forge", "script", f"script/{temp_name}",
                "--rpc-url", "http://127.0.0.1:8545",
                "--broadcast"
            ]

            try:
                # Execute from the simulation_env working directory.
                run_cwd = os.path.join(self.workspace, "simulation_env")
                proc = subprocess.run(
                    cmd,
                    cwd=run_cwd,
                    capture_output=True,
                    text=True
                )

                # Generated scripts use try/catch, so return code 0 means the
                # regression script completed without an infrastructure failure.
                if proc.returncode == 0:
                    passed += 1
                    status = "✅ PASS"
                else:
                    status = "❌ FAIL"
                    # proc.stderr contains diagnostic details for failures.

                results.append(f"{script_name}: {status}")

            except Exception as e:
                results.append(f"{script_name}: Error {str(e)}")
            finally:
                # Remove the temporary script.
                if os.path.exists(temp_path):
                    os.remove(temp_path)

        pass_rate = (passed / total) * 100 if total > 0 else 0.0
        self.logger(f"   📊 Regression Result: {passed}/{total} ({pass_rate:.1f}%) scripts executed successfully.")

        return {
            "total": total,
            "passed": passed,
            "rate": pass_rate,
            "details": results
        }
